.TH cococs 1 "Jun 22, 2009" "Coco/R Compiler Generator (C-Sharp Version)"

.SH NAME
cococs \- Coco/R Compiler Generator (C-Sharp Version)

.SH HINT
By default cococs expects the Parser.frame and Scanner.frame file to be
in the same directory as the grammar (atg-file) to translate. As the 
frame files are architecture independent, the default frame files can be
found in /usr/share/coco-cs/.

.SH SEE ALSO

See package coco-doc for documentation.

