
/*-------------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than
Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
using System.IO;



using System;

namespace at.jku.ssw.Coco {



public class Parser {
	public const int _EOF = 0;
	public const int _ident = 1;
	public const int _number = 2;
	public const int _string = 3;
	public const int _badString = 4;
	public const int _char = 5;
	public const int maxT = 47;
	public const int _ddtSym = 48;
	public const int _directive = 49;

	const bool T = true;
	const bool x = false;
	const int minErrDist = 2;

	public Scanner scanner;
	public Errors  errors;

	public Token t;    //!< last recognized token
	public Token la;   //!< lookahead token
	int errDist = minErrDist;

const int isIdent   = 0;
	const int isLiteral = 1;

	public Tab tab;             // other Coco objects referenced in this ATG
	public DFA dfa;
	public ParserGen pgen;

	bool   genScanner = false;
	string tokenString;         // used in declarations of literal tokens
	string noString = "-none-"; // used in declarations of literal tokens

/*-------------------------------------------------------------------------*/



	public Parser(Scanner scanner) {
		this.scanner = scanner;
		errors = new Errors();
		// user-defined initialization:

	}



	void SynErr (int n) {
		if (errDist >= minErrDist) errors.SynErr(la.line, la.col, n);
		errDist = 0;
	}

	public void SemErr (string msg) {
		if (errDist >= minErrDist) errors.SemErr(t.line, t.col, msg);
		errDist = 0;
	}

	void Get () {
		for (;;) {
			t = la;
			la = scanner.Scan();
			if (la.kind <= maxT) { ++errDist; break; }
				if (la.kind == 48) {
				tab.SetDDT(la.val); 
				}
				if (la.kind == 49) {
				tab.DispatchDirective(la.val); 
				}

			la = t;
		}
	}

	void Expect (int n) {
		if (la.kind==n) Get(); else { SynErr(n); }
	}

	bool StartOf (int s) {
		return set[s, la.kind];
	}

	void ExpectWeak (int n, int follow) {
		if (la.kind == n) Get();
		else {
			SynErr(n);
			while (!StartOf(follow)) Get();
		}
	}


	bool WeakSeparator(int n, int syFol, int repFol) {
		int kind = la.kind;
		if (kind == n) {Get(); return true;}
		else if (StartOf(repFol)) {return false;}
		else {
			SynErr(n);
			while (!(set[syFol, kind] || set[repFol, kind] || set[0, kind])) {
				Get();
				kind = la.kind;
			}
			return StartOf(syFol);
		}
	}


	void Coco() {
		Symbol sym; Graph g; string grammarName; CharSet s; 
		if (la.kind == 6) {
			Get();
			int beg = t.pos + t.val.Length; 
			while (StartOf(1)) {
				Get();
			}
			tab.copyPos = new Position(beg, la.pos, 0); 
			Expect(7);
		}
		if (StartOf(2)) {
			Get();
			int beg = t.pos; 
			while (StartOf(3)) {
				Get();
			}
			pgen.preamblePos = new Position(beg, la.pos, 0); 
		}
		Expect(8);
		genScanner = true; 
		Expect(1);
		grammarName = t.val; 
		if (StartOf(4)) {
			Get();
			int beg = t.pos; 
			while (StartOf(4)) {
				Get();
			}
			pgen.semDeclPos = new Position(beg, la.pos, 0); 
		}
		if (la.kind == 9) {
			Get();
			if (StartOf(5)) {
				Get();
				int beg = t.pos; 
				while (StartOf(5)) {
					Get();
				}
				pgen.initCodePos = new Position(beg, la.pos, 0); 
			}
			Expect(10);
		}
		if (la.kind == 11) {
			Get();
			if (StartOf(6)) {
				Get();
				int beg = t.pos; 
				while (StartOf(6)) {
					Get();
				}
				pgen.deinitCodePos = new Position(beg, la.pos, 0); 
			}
			Expect(12);
		}
		if (la.kind == 13) {
			Get();
			dfa.ignoreCase = true; 
		}
		if (la.kind == 14) {
			Get();
			while (la.kind == 1) {
				SetDecl();
			}
		}
		if (la.kind == 15) {
			Get();
			while (la.kind == 1 || la.kind == 3 || la.kind == 5) {
				TokenDecl(Node.t);
			}
		}
		if (la.kind == 16) {
			Get();
			while (la.kind == 1 || la.kind == 3 || la.kind == 5) {
				TokenDecl(Node.pr);
			}
		}
		while (la.kind == 17) {
			Get();
			Graph g1, g2; bool nested = false; 
			Expect(18);
			TokenExpr(out g1);
			Expect(19);
			TokenExpr(out g2);
			if (la.kind == 20) {
				Get();
				nested = true; 
			}
			dfa.NewComment(g1.l, g2.l, nested); 
		}
		while (la.kind == 21) {
			Get();
			Set(out s);
			tab.ignored.Or(s); 
		}
		while (!(la.kind == 0 || la.kind == 22)) {SynErr(48); Get();}
		Expect(22);
		if (genScanner) dfa.MakeDeterministic();
		tab.DeleteNodes();
		
		while (la.kind == 1) {
			Get();
			sym = tab.FindSym(t.val);
			bool undef = (sym == null);
			if (undef) sym = tab.NewSym(Node.nt, t.val, t.line);
			else {
			  if (sym.typ == Node.nt) {
			    if (sym.graph != null)
			      SemErr("name declared twice");
			  } else SemErr("this symbol kind not allowed on left side of production");
			  sym.line = t.line;
			}
			bool noAttrs = (sym.attrPos == null);
			sym.attrPos = null;
			
			if (la.kind == 30 || la.kind == 32) {
				AttrDecl(sym);
			}
			if (!undef && noAttrs != (sym.attrPos == null))
			 SemErr("attribute mismatch between declaration and use of this symbol");
			
			if (la.kind == 45) {
				SemText(out sym.semPos);
			}
			ExpectWeak(23, 7);
			Expression(out g);
			sym.graph = g.l;
			tab.Finish(g);
			
			ExpectWeak(24, 8);
		}
		Expect(25);
		Expect(1);
		if (grammarName != t.val)
		 SemErr("name does not match grammar name");
		tab.gramSy = tab.FindSym(grammarName);
		if (tab.gramSy == null)
		  SemErr("missing production for grammar name");
		else {
		  sym = tab.gramSy;
		  if (sym.attrPos != null)
		    SemErr("grammar symbol must not have attributes");
		}
		tab.noSym = tab.NewSym(Node.t, "???", 0); // noSym gets highest number
		tab.SetupAnys();
		tab.RenumberPragmas();
		if (tab.ddt[2]) tab.PrintNodes();
		if (errors.count == 0) {
		  Console.WriteLine("checking");
		  tab.CompSymbolSets();
		  if (tab.ddt[7]) tab.XRef();
		  if (tab.GrammarOk()) {
		    Console.Write("parser");
		    pgen.WriteParser();
		    if (genScanner) {
		      Console.Write(" + scanner");
		      dfa.WriteScanner();
		      if (tab.ddt[0]) dfa.PrintStates();
		    }
		    Console.WriteLine(" generated");
		    if (tab.ddt[8]) {
		      tab.PrintStatistics();
		      pgen.PrintStatistics();
		    }
		  }
		}
		if (tab.ddt[6]) tab.PrintSymbolTable();
		
		Expect(24);
	}

	void SetDecl() {
		CharSet s; 
		Expect(1);
		string name = t.val;
		CharClass c = tab.FindCharClass(name);
		if (c != null) SemErr("name declared twice");
		
		Expect(23);
		Set(out s);
		if (s.Elements() == 0) SemErr("character set must not be empty");
		tab.NewCharClass(name, s);
		
		Expect(24);
	}

	void TokenDecl(int typ) {
		string name; int kind; Symbol sym; Graph g; 
		Sym(out name, out kind);
		sym = tab.FindSym(name);
		if (sym != null) SemErr("name declared twice");
		else {
		  sym = tab.NewSym(typ, name, t.line);
		  sym.tokenKind = Symbol.fixedToken;
		}
		tokenString = null;
		
		while (!(StartOf(9))) {SynErr(49); Get();}
		if (la.kind == 23) {
			Get();
			TokenExpr(out g);
			Expect(24);
			if (kind == isLiteral) SemErr("a literal must not be declared with a structure");
			tab.Finish(g);
			if (tokenString == null || tokenString.Equals(noString))
			  dfa.ConvertToStates(g.l, sym);
			else { // TokenExpr is a single string
			  if (tab.literals[tokenString] != null)
			    SemErr("token string declared twice");
			  tab.literals[tokenString] = sym;
			  dfa.MatchLiteral(tokenString, sym);
			}
			
		} else if (StartOf(10)) {
			if (kind == isIdent) genScanner = false;
			else dfa.MatchLiteral(sym.name, sym);
			
		} else SynErr(50);
		if (la.kind == 45) {
			SemText(out sym.semPos);
			if (typ != Node.pr) SemErr("semantic action not allowed here"); 
		}
	}

	void TokenExpr(out Graph g) {
		Graph g2; 
		TokenTerm(out g);
		bool first = true; 
		while (WeakSeparator(34,11,12) ) {
			TokenTerm(out g2);
			if (first) { tab.MakeFirstAlt(g); first = false; }
			tab.MakeAlternative(g, g2);
			
		}
	}

	void Set(out CharSet s) {
		CharSet s2; 
		SimSet(out s);
		while (la.kind == 26 || la.kind == 27) {
			if (la.kind == 26) {
				Get();
				SimSet(out s2);
				s.Or(s2); 
			} else {
				Get();
				SimSet(out s2);
				s.Subtract(s2); 
			}
		}
	}

	void AttrDecl(Symbol sym) {
		if (la.kind == 30) {
			Get();
			int beg = la.pos; int col = la.col; 
			while (StartOf(13)) {
				if (StartOf(14)) {
					Get();
				} else {
					Get();
					SemErr("bad string in attributes"); 
				}
			}
			Expect(31);
			if (t.pos > beg)
			 sym.attrPos = new Position(beg, t.pos, col); 
		} else if (la.kind == 32) {
			Get();
			int beg = la.pos; int col = la.col; 
			while (StartOf(15)) {
				if (StartOf(16)) {
					Get();
				} else {
					Get();
					SemErr("bad string in attributes"); 
				}
			}
			Expect(33);
			if (t.pos > beg)
			 sym.attrPos = new Position(beg, t.pos, col); 
		} else SynErr(51);
	}

	void SemText(out Position pos) {
		Expect(45);
		int beg = la.pos; int col = la.col; 
		while (StartOf(17)) {
			if (StartOf(18)) {
				Get();
			} else if (la.kind == 4) {
				Get();
				SemErr("bad string in semantic action"); 
			} else {
				Get();
				SemErr("missing end of previous semantic action"); 
			}
		}
		Expect(46);
		pos = new Position(beg, t.pos, col); 
	}

	void Expression(out Graph g) {
		Graph g2; 
		Term(out g);
		bool first = true; 
		while (WeakSeparator(34,19,20) ) {
			Term(out g2);
			if (first) { tab.MakeFirstAlt(g); first = false; }
			tab.MakeAlternative(g, g2);
			
		}
	}

	void SimSet(out CharSet s) {
		int n1, n2; s = new CharSet(); 
		if (la.kind == 1) {
			Get();
			CharClass c = tab.FindCharClass(t.val);
			if (c == null) SemErr("undefined name"); else s.Or(c.set);
			
		} else if (la.kind == 3) {
			Get();
			string name = t.val;
			name = tab.Unescape(name.Substring(1, name.Length-2));
			foreach (char ch in name)
			  if (dfa.ignoreCase) s.Set(char.ToLower(ch));
			  else s.Set(ch); 
		} else if (la.kind == 5) {
			Char(out n1);
			s.Set(n1); 
			if (la.kind == 28) {
				Get();
				Char(out n2);
				for (int i = n1; i <= n2; i++) s.Set(i); 
			}
		} else if (la.kind == 29) {
			Get();
			s = new CharSet(); s.Fill(); 
		} else SynErr(52);
	}

	void Char(out int n) {
		Expect(5);
		string name = t.val; n = 0;
		name = tab.Unescape(name.Substring(1, name.Length-2));
		if (name.Length == 1) n = name[0];
		else SemErr("unacceptable character value");
		if (dfa.ignoreCase && (char)n >= 'A' && (char)n <= 'Z') n += 32;
		
	}

	void Sym(out string name, out int kind) {
		name = "???"; kind = isIdent; 
		if (la.kind == 1) {
			Get();
			kind = isIdent; name = t.val; 
		} else if (la.kind == 3 || la.kind == 5) {
			if (la.kind == 3) {
				Get();
				name = t.val; 
			} else {
				Get();
				name = "\"" + t.val.Substring(1, t.val.Length-2) + "\""; 
			}
			kind = isLiteral;
			if (dfa.ignoreCase) name = name.ToLower();
			if (name.IndexOf(' ') >= 0)
			  SemErr("literal tokens must not contain blanks"); 
		} else SynErr(53);
	}

	void Term(out Graph g) {
		Graph g2; Node rslv = null; g = null; 
		if (StartOf(21)) {
			if (la.kind == 43) {
				rslv = tab.NewNode(Node.rslv, null, la.line); 
				Resolver(out rslv.pos);
				g = new Graph(rslv); 
			}
			Factor(out g2);
			if (rslv != null) tab.MakeSequence(g, g2);
			else g = g2;
			
			while (StartOf(22)) {
				Factor(out g2);
				tab.MakeSequence(g, g2); 
			}
		} else if (StartOf(23)) {
			g = new Graph(tab.NewNode(Node.eps, null, 0)); 
		} else SynErr(54);
		if (g == null) // invalid start of Term
		 g = new Graph(tab.NewNode(Node.eps, null, 0));
		
	}

	void Resolver(out Position pos) {
		Expect(43);
		Expect(36);
		int beg = la.pos; int col = la.col; 
		Condition();
		pos = new Position(beg, t.pos, col); 
	}

	void Factor(out Graph g) {
		string name; int kind; Position pos; bool weak = false;
		g = null;
		
		switch (la.kind) {
		case 1: case 3: case 5: case 35: {
			if (la.kind == 35) {
				Get();
				weak = true; 
			}
			Sym(out name, out kind);
			Symbol sym = tab.FindSym(name);
			if (sym == null && kind == isLiteral)
			  sym = tab.literals[name] as Symbol;
			bool undef = (sym == null);
			if (undef) {
			  if (kind == isIdent)
			    sym = tab.NewSym(Node.nt, name, 0);  // forward nt
			  else if (genScanner) {
			    sym = tab.NewSym(Node.t, name, t.line);
			    dfa.MatchLiteral(sym.name, sym);
			  } else {  // undefined string in production
			    SemErr("undefined string in production");
			    sym = tab.eofSy;  // dummy
			  }
			}
			int typ = sym.typ;
			if (typ != Node.t && typ != Node.nt)
			  SemErr("this symbol kind is not allowed in a production");
			if (weak)
			  if (typ == Node.t) typ = Node.wt;
			  else SemErr("only terminals may be weak");
			Node p = tab.NewNode(typ, sym, t.line);
			g = new Graph(p);
			
			if (la.kind == 30 || la.kind == 32) {
				Attribs(p);
				if (kind == isLiteral) SemErr("a literal must not have attributes"); 
			}
			if (undef)
			 sym.attrPos = p.pos;  // dummy
			else if ((p.pos == null) != (sym.attrPos == null))
			  SemErr("attribute mismatch between declaration and use of this symbol");
			
			break;
		}
		case 36: {
			Get();
			Expression(out g);
			Expect(37);
			break;
		}
		case 38: {
			Get();
			Expression(out g);
			Expect(39);
			tab.MakeOption(g); 
			break;
		}
		case 40: {
			Get();
			Expression(out g);
			Expect(41);
			tab.MakeIteration(g); 
			break;
		}
		case 45: {
			SemText(out pos);
			Node p = tab.NewNode(Node.sem, null, 0);
			p.pos = pos;
			g = new Graph(p);
			
			break;
		}
		case 29: {
			Get();
			Node p = tab.NewNode(Node.any, null, 0);  // p.set is set in tab.SetupAnys
			g = new Graph(p);
			
			break;
		}
		case 42: {
			Get();
			Node p = tab.NewNode(Node.sync, null, 0);
			g = new Graph(p);
			
			break;
		}
		default: SynErr(55); break;
		}
		if (g == null) // invalid start of Factor
		 g = new Graph(tab.NewNode(Node.eps, null, 0));
		
	}

	void Attribs(Node p) {
		if (la.kind == 30) {
			Get();
			int beg = la.pos; int col = la.col; 
			while (StartOf(13)) {
				if (StartOf(14)) {
					Get();
				} else {
					Get();
					SemErr("bad string in attributes"); 
				}
			}
			Expect(31);
			if (t.pos > beg) p.pos = new Position(beg, t.pos, col); 
		} else if (la.kind == 32) {
			Get();
			int beg = la.pos; int col = la.col; 
			while (StartOf(15)) {
				if (StartOf(16)) {
					Get();
				} else {
					Get();
					SemErr("bad string in attributes"); 
				}
			}
			Expect(33);
			if (t.pos > beg) p.pos = new Position(beg, t.pos, col); 
		} else SynErr(56);
	}

	void Condition() {
		while (StartOf(24)) {
			if (la.kind == 36) {
				Get();
				Condition();
			} else {
				Get();
			}
		}
		Expect(37);
	}

	void TokenTerm(out Graph g) {
		Graph g2; 
		TokenFactor(out g);
		while (StartOf(11)) {
			TokenFactor(out g2);
			tab.MakeSequence(g, g2); 
		}
		if (la.kind == 44) {
			Get();
			Expect(36);
			TokenExpr(out g2);
			tab.SetContextTrans(g2.l);
			dfa.hasCtxMoves = true;
			tab.MakeSequence(g, g2); 
			Expect(37);
		}
	}

	void TokenFactor(out Graph g) {
		string name; int kind; g = null; 
		if (la.kind == 1 || la.kind == 3 || la.kind == 5) {
			Sym(out name, out kind);
			if (kind == isIdent) {
			 CharClass c = tab.FindCharClass(name);
			 if (c == null) {
			   SemErr("undefined name");
			   c = tab.NewCharClass(name, new CharSet());
			 }
			 Node p = tab.NewNode(Node.clas, null, 0); p.val = c.n;
			 g = new Graph(p);
			 tokenString = noString;
			} else { // str
			  g = tab.StrToGraph(name);
			  if (tokenString == null) tokenString = name;
			  else tokenString = noString;
			}
			
		} else if (la.kind == 36) {
			Get();
			TokenExpr(out g);
			Expect(37);
		} else if (la.kind == 38) {
			Get();
			TokenExpr(out g);
			Expect(39);
			tab.MakeOption(g); 
		} else if (la.kind == 40) {
			Get();
			TokenExpr(out g);
			Expect(41);
			tab.MakeIteration(g); 
		} else SynErr(57);
		if (g == null) // invalid start of TokenFactor
		 g = new Graph(tab.NewNode(Node.eps, null, 0)); 
	}



	public void Parse() {
		la = new Token();
		la.val = "";
		Get();
		Coco();
		Expect(0); // expect end-of-file automatically added

	}

	static readonly bool[,] set = {
		{T,T,x,T, x,T,x,x, x,x,x,x, x,x,x,x, T,T,x,x, x,T,T,T, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,T,x,x, x},
		{x,T,T,T, T,T,T,x, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{x,T,T,T, T,T,x,T, x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{x,T,T,T, T,T,T,T, x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{x,T,T,T, T,T,T,T, T,x,T,x, T,x,x,x, x,x,T,T, T,x,x,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{x,T,T,T, T,T,T,T, T,T,x,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{x,T,T,T, T,T,T,T, T,T,T,T, x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{T,T,x,T, x,T,x,x, x,x,x,x, x,x,x,x, T,T,x,x, x,T,T,T, T,x,x,x, x,T,x,x, x,x,T,T, T,x,T,x, T,x,T,T, x,T,x,x, x},
		{T,T,x,T, x,T,x,x, x,x,x,x, x,x,x,x, T,T,x,x, x,T,T,T, x,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,T,x,x, x},
		{T,T,x,T, x,T,x,x, x,x,x,x, x,x,x,x, T,T,x,x, x,T,T,T, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,T,x,x, x},
		{x,T,x,T, x,T,x,x, x,x,x,x, x,x,x,x, T,T,x,x, x,T,T,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,T,x,x, x},
		{x,T,x,T, x,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, T,x,T,x, T,x,x,x, x,x,x,x, x},
		{x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,T,x,T, T,T,T,x, T,x,x,x, x,x,x,x, x,x,x,x, x,T,x,T, x,T,x,x, x,x,x,x, x},
		{x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,x, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{x,T,T,T, x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,x, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,x,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{x,T,T,T, x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,x,T,T, T,T,T,T, T,T,T,T, T,T,T,T, x},
		{x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,x,T, x},
		{x,T,T,T, x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,x,x,T, x},
		{x,T,x,T, x,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, T,x,x,x, x,T,x,x, x,x,T,T, T,T,T,T, T,T,T,T, x,T,x,x, x},
		{x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, T,x,x,x, x,x,x,x, x,x,x,x, x,T,x,T, x,T,x,x, x,x,x,x, x},
		{x,T,x,T, x,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,T,x,x, x,x,x,T, T,x,T,x, T,x,T,T, x,T,x,x, x},
		{x,T,x,T, x,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,T,x,x, x,x,x,T, T,x,T,x, T,x,T,x, x,T,x,x, x},
		{x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, T,x,x,x, x,x,x,x, x,x,T,x, x,T,x,T, x,T,x,x, x,x,x,x, x},
		{x,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,T,T,T, T,x,T,T, T,T,T,T, T,T,T,T, x}

	};
} // end Parser


public class Errors {
	public int count = 0;                                    // number of errors detected
	public System.IO.TextWriter errorStream = Console.Out;   // error messages go to this stream
  public string errMsgFormat = "-- line {0} col {1}: {2}"; // 0=line, 1=column, 2=text

	public void SynErr (int line, int col, int n) {
		string s;
		switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "ident expected"; break;
			case 2: s = "number expected"; break;
			case 3: s = "string expected"; break;
			case 4: s = "badString expected"; break;
			case 5: s = "char expected"; break;
			case 6: s = "\"[copy]\" expected"; break;
			case 7: s = "\"[/copy]\" expected"; break;
			case 8: s = "\"COMPILER\" expected"; break;
			case 9: s = "\"[initialize]\" expected"; break;
			case 10: s = "\"[/initialize]\" expected"; break;
			case 11: s = "\"[destroy]\" expected"; break;
			case 12: s = "\"[/destroy]\" expected"; break;
			case 13: s = "\"IGNORECASE\" expected"; break;
			case 14: s = "\"CHARACTERS\" expected"; break;
			case 15: s = "\"TOKENS\" expected"; break;
			case 16: s = "\"PRAGMAS\" expected"; break;
			case 17: s = "\"COMMENTS\" expected"; break;
			case 18: s = "\"FROM\" expected"; break;
			case 19: s = "\"TO\" expected"; break;
			case 20: s = "\"NESTED\" expected"; break;
			case 21: s = "\"IGNORE\" expected"; break;
			case 22: s = "\"PRODUCTIONS\" expected"; break;
			case 23: s = "\"=\" expected"; break;
			case 24: s = "\".\" expected"; break;
			case 25: s = "\"END\" expected"; break;
			case 26: s = "\"+\" expected"; break;
			case 27: s = "\"-\" expected"; break;
			case 28: s = "\"..\" expected"; break;
			case 29: s = "\"ANY\" expected"; break;
			case 30: s = "\"<\" expected"; break;
			case 31: s = "\">\" expected"; break;
			case 32: s = "\"<.\" expected"; break;
			case 33: s = "\".>\" expected"; break;
			case 34: s = "\"|\" expected"; break;
			case 35: s = "\"WEAK\" expected"; break;
			case 36: s = "\"(\" expected"; break;
			case 37: s = "\")\" expected"; break;
			case 38: s = "\"[\" expected"; break;
			case 39: s = "\"]\" expected"; break;
			case 40: s = "\"{\" expected"; break;
			case 41: s = "\"}\" expected"; break;
			case 42: s = "\"SYNC\" expected"; break;
			case 43: s = "\"IF\" expected"; break;
			case 44: s = "\"CONTEXT\" expected"; break;
			case 45: s = "\"(.\" expected"; break;
			case 46: s = "\".)\" expected"; break;
			case 47: s = "??? expected"; break;
			case 48: s = "this symbol not expected in Coco"; break;
			case 49: s = "this symbol not expected in TokenDecl"; break;
			case 50: s = "invalid TokenDecl"; break;
			case 51: s = "invalid AttrDecl"; break;
			case 52: s = "invalid SimSet"; break;
			case 53: s = "invalid Sym"; break;
			case 54: s = "invalid Term"; break;
			case 55: s = "invalid Factor"; break;
			case 56: s = "invalid Attribs"; break;
			case 57: s = "invalid TokenFactor"; break;

			default: s = "error " + n; break;
		}
		errorStream.WriteLine(errMsgFormat, line, col, s);
		count++;
	}

	public void SemErr (int line, int col, string s) {
		errorStream.WriteLine(errMsgFormat, line, col, s);
		count++;
	}

	public void SemErr (string s) {
		errorStream.WriteLine(s);
		count++;
	}

	public void Warning (int line, int col, string s) {
		errorStream.WriteLine(errMsgFormat, line, col, s);
	}

	public void Warning(string s) {
		errorStream.WriteLine(s);
	}
} // Errors


public class FatalError: Exception {
	public FatalError(string m): base(m) {}
}

} // end namespace
